.PHONY build:
	@go build -o bin ~/go/src/github.com/telegram-bots/read-adviser-bot/main.go

.PHONY run:
	@go run ~/go/src/github.com/telegram-bots/read-adviser-bot/main.go

.PHONY fmt:
	@go fmt -w -s .

.PHONY cwd:
	@cd ~/go/src/github.com/telegram-bots/read-adviser-bot